
"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

"""
def findTheDifference(s, t):
    """
    Haha, I like the last line trick not to use ZIP_LONGEST
    """
    s = sorted(s)
    t = sorted(t)
    for s1, s2 in zip(s, t):
        if s1 != s2:
            return s2
    return t[-1]
